# Site settings
title: PrivacyTracker
email: fishdev@github.com
url: https://fishdev.github.io/PrivacyTracker
description: "A user-centered browsing plugin design to understand online tracking, helping you find out who's stalking you on the web"
github_username: fishdev
baseurl: /PrivacyTracker

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Ashwin Srinivasan

# Build settings
markdown: kramdown
permalink: pretty
